function [f,v] = createRectangle(w,h,d)
v =     [-w -h -d; ...
          w -h -d; ...
         -w  h -d; ...
          w  h -d; ...
         -w -h  d; ...
          w -h  d; ...
         -w  h  d; ...
          w  h  d];
f =     [3 4 8 7; ...
         4 2 6 8; ...
         2 1 5 6; ...
         1 3 7 5; ...
         7 8 6 5; ...
         1 2 4 3];